# Exploration interactive des données PhishTank

Ce notebook explore le flux public PhishTank enregistré dans `../data/urls_phishtank_brutes.csv`.
PhishTank fournit un flux public de phishing vérifié, donc ce notebook et le script associé fonctionnent sans clé API.

In [13]:
from pathlib import Path
from io import StringIO
from urllib.request import Request, urlopen

import pandas as pd

output_path = Path("../data/urls_phishtank_brutes.csv")
phishtank_url = "https://data.phishtank.com/data/online-valid.csv"
request = Request(phishtank_url, headers={"User-Agent": "phishtank-notebook/1.0"})

if output_path.exists():
    df = pd.read_csv(output_path)
else:
    with urlopen(request) as response:
        csv_text = response.read().decode("utf-8", errors="replace")
    df = pd.read_csv(StringIO(csv_text))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(output_path, index=False)

display(df.head())

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9480059,https://6u3r8h3r.hair/gqdn1ziy/kgRlUX/pSkIlz,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T13:07:51+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
1,9480058,https://4je7u3.hair/gqdn1ziy/kgRlUX/pSkIlz,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T13:05:51+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
2,9480054,https://obramaxbuscador.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:59:54+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
3,9480053,http://allegrolokalnie.lokalna-ofera953321.lol...,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:55:22+00:00,yes,2026-07-15T13:13:17+00:00,yes,Allegro
4,9480049,https://safradocumentos.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:42:33+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other

In [14]:
df.shape

(65046, 8)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 65046 entries, 0 to 65045
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   phish_id           65046 non-null  int64
 1   url                65046 non-null  str
 2   phish_detail_url   65046 non-null  str
 3   submission_time    65046 non-null  str
 4   verified           65046 non-null  str
 5   verification_time  65046 non-null  str
 6   online             65046 non-null  str
 7   target             65046 non-null  str
dtypes: int64(1), str(7)
memory usage: 4.0 MB

In [16]:
df.describe(include="all")

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
count,6.504600e+04,65046,65046,65046,65046,65046,65046,65046
unique,NaN,65043,65046,63714,1,23068,1,99
top,NaN,https://storage.cloud.google.com/1lordman1man3...,http://www.phishtank.com/phish_detail.php?phis...,2023-04-27T21:36:22+00:00,yes,2026-02-13T03:52:32+00:00,yes,Other
freq,NaN,3,1,6,65046,75,65046,59207
mean,8.997623e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.755681e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.123978e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,8.684442e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,9.178666e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,9.412508e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,9.480059e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df.isna().sum()

phish_id             0
url                  0
phish_detail_url     0
submission_time      0
verified             0
verification_time    0
online               0
target               0
dtype: int64

In [18]:
df.head(10)

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,9480059,https://6u3r8h3r.hair/gqdn1ziy/kgRlUX/pSkIlz,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T13:07:51+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
1,9480058,https://4je7u3.hair/gqdn1ziy/kgRlUX/pSkIlz,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T13:05:51+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
2,9480054,https://obramaxbuscador.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:59:54+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
3,9480053,http://allegrolokalnie.lokalna-ofera953321.lol...,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:55:22+00:00,yes,2026-07-15T13:13:17+00:00,yes,Allegro
4,9480049,https://safradocumentos.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:42:33+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
5,9480047,https://verificar-nu-saldo.vercel.app/,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:41:19+00:00,yes,2026-07-15T13:13:17+00:00,yes,Other
6,9480042,https://kleinanzeigen-bestellung.jungleegames....,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:32:19+00:00,yes,2026-07-15T12:42:53+00:00,yes,Other
7,9480041,https://kleinanzeigen-bestellung.jungleegames....,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:32:18+00:00,yes,2026-07-15T12:42:53+00:00,yes,Other
8,9480040,https://kleinanzeigen-bestellung.jungleegames....,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:32:17+00:00,yes,2026-07-15T12:42:53+00:00,yes,Other
9,9480034,https://kleinanzeigen-bestellung.jungleegames....,http://www.phishtank.com/phish_detail.php?phis...,2026-07-15T12:30:19+00:00,yes,2026-07-15T12:35:40+00:00,yes,Other

## Observations après exécution

- Le flux public PhishTank contient **65 046 URLs** dans ce notebook.
- Les colonnes **verified**, **online** et **target** sont bien présentes.
- Il n'y a **aucune valeur manquante** dans les colonnes du jeu de données.
- Le jeu de données est bien centré sur du **phishing vérifié** : les colonnes `verified` et `online` sont toutes les deux à `yes` pour l'ensemble des lignes.
- La colonne `target` contient **99 valeurs distinctes**, avec une forte domination de `Other`.